version: '3.8'

services:
  discount_postgres:
    image: postgres
    container_name: discount_postgres
    read_only: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=discountDb
    expose:
      - "54324"
    ports:
      - "54324:54324"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - discount_postgres_volume:/var/lib/postgresql/data
    command: -p 54324

  library_postgres:
    image: postgres
    container_name: library_postgres
    read_only: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=libraryDb
    expose:
      - "54323"
    ports:
      - "54323:54323"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    command: -p 54323


volumes:
  postgres-volume:
  discount_postgres_volume:
